development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: api.meet.up123
  :password: meetup123
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: api.meet.up123
  :password: meetup123
  :enable_starttls_auto: true
